apiVersion: v1
kind: Service
metadata:
  name: trend-app
  labels:
    app: trend-app
  annotations:
    # If you want an NLB on EKS (default for many clusters, but you can force it):
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # For internet-facing LB (default). For internal, set "internal".
    # service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: trend-app
  ports:
    - name: http
      port: 3000        # external LB port (per requirement)
      targetPort: 80    # container (nginx) port
