apiVersion: v1
kind: Service
metadata:
  name: trend-app
  namespace: trend-app
  labels:
    app: trend-app
spec:
  type: LoadBalancer
  selector:
    app: trend-app
  ports:
    - name: http
      port: 3000        # public LB port
      targetPort: 80    # container listens on 80 (nginx)
      protocol: TCP
