apiVersion: v1
kind: Service
metadata:
  name: trend-web-service
  labels:
    app: trend-web
spec:
  type: LoadBalancer
  selector:
    app: trend-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
